type: patch_policy
dataset_name: franka_insertion
dataset_class: factr_pickle.FactrPickleDataset
data_directory: "${env_vars.datasets.franka_insertion}"
language_instruction: "insert the object into the target"

# Robot constants
# action_dim: 7              # eef_delta (6) + binary gripper (1)
action_dim: 8
num_actions_chunk: 8
proprio_dim: 0
normalization_type: "bounds_q99"
num_views: 2               # /realsense/side/im + /realsense/wrist/im
# action_type: "joint_absolute"
# goal_dim: 0
# goal_source: "none"

# Data slicing
window_size: 8
train_fraction: 0.95
subset_fraction: null

# Dataset-specific args
prefetch: false
image_topics: ["/realsense/side/im", "/realsense/wrist/im"]  # side = primary, wrist = secondary
